In [9]:
import os
import pandas as pd

In [10]:
directory = 'C:/Users/FANNY MARIA D SOUZA/Capstone/DemographicInfo/'

In [11]:
df=pd.read_csv('blockdesignscore.csv')

#### Demographic Info - Complex Pie

In [12]:
demo_complexpie=pd.read_csv('Features_ComplexPie_Action.csv')

In [13]:
demo_complexpie

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Apple Interactions - Add Apples,...,Put pie in oven,Add butter,Add crust top,Add water,Error to Actions Ratio,Object Count - Add sugar,Object Count - Add apples,Object Count - Add cinnamon,Object Count - Stir bowl,Object Count - Add bottom crust
0,C001,Female,36,171,319.556571,10,161,21.491310,20.968374,49,...,10,16,10,3,0.058480,12,75,26,11,2
1,C003,Female,58,172,362.351788,10,162,35.154070,29.176267,56,...,10,9,5,2,0.058140,5,100,2,9,7
2,C006,Male,42,199,570.236635,24,175,56.950739,23.036730,25,...,11,9,4,25,0.120603,11,72,11,24,3
3,C008,Female,34,254,466.281171,27,227,58.660959,47.043500,87,...,10,16,7,3,0.106299,9,153,5,16,3
4,C009,Female,24,198,438.425413,2,196,47.728880,32.351198,73,...,5,20,9,2,0.010101,11,113,4,17,5
5,C012,Female,54,247,532.936495,8,239,53.877959,37.176239,83,...,8,12,11,6,0.032389,7,131,14,37,7
6,C013,Female,48,266,580.830070,22,244,61.982680,45.411052,88,...,7,20,4,12,0.082707,7,156,6,13,6
7,C016,Male,39,208,517.807503,13,195,46.610894,30.500671,68,...,6,21,21,6,0.062500,7,106,10,9,9
8,C017,Male,36,170,369.351203,11,159,35.590809,20.441936,37,...,8,15,5,1,0.064706,9,48,2,59,6
9,C020,Female,30,222,565.967667,7,215,34.357832,23.506672,33,...,11,15,8,3,0.031532,11,52,78,19,8
10,C021,Female,29,191,433.172928,14,177,53.824557,17.917995,8,...,21,17,6,7,0.073298,61,20,26,3,14
11,C024,Female,42,194,288.786743,18,176,28.894366,29.007836,71,...,15,9,12,1,0.092784,5,102,7,8,16
12,C025,Female,24,159,359.124353,17,142,33.020450,16.108157,31,...,35,16,6,2,0.106918,5,39,41,3,2
13,C028,Male,50,204,858.494425,18,186,90.978381,35.432651,91,...,24,14,6,1,0.088235,13,120,2,5,2
14,C029,Male,34,142,348.855143,6,136,42.245812,19.796235,31,...,0,6,0,3,0.042254,30,59,6,0,0
15,C032,Female,63,305,556.955603,20,285,29.614194,23.652023,36,...,13,35,22,31,0.065574,13,72,66,21,6

In [14]:
df = df[['Q1','Q2.1']].rename(columns={'Q1': 'Participant', 'Q2.1': 'Age'})
df_complexpie = pd.merge( demo_complexpie, df , on='Participant', how='inner')
df_complexpie

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Apple Interactions - Add Apples,...,Add butter,Add crust top,Add water,Error to Actions Ratio,Object Count - Add sugar,Object Count - Add apples,Object Count - Add cinnamon,Object Count - Stir bowl,Object Count - Add bottom crust,Age
0,C001,Female,36,171,319.556571,10,161,21.491310,20.968374,49,...,16,10,3,0.058480,12,75,26,11,2,21
1,C003,Female,58,172,362.351788,10,162,35.154070,29.176267,56,...,9,5,2,0.058140,5,100,2,9,7,25
2,C006,Male,42,199,570.236635,24,175,56.950739,23.036730,25,...,9,4,25,0.120603,11,72,11,24,3,35
3,C008,Female,34,254,466.281171,27,227,58.660959,47.043500,87,...,16,7,3,0.106299,9,153,5,16,3,25
4,C009,Female,24,198,438.425413,2,196,47.728880,32.351198,73,...,20,9,2,0.010101,11,113,4,17,5,26
5,C012,Female,54,247,532.936495,8,239,53.877959,37.176239,83,...,12,11,6,0.032389,7,131,14,37,7,25
6,C013,Female,48,266,580.830070,22,244,61.982680,45.411052,88,...,20,4,12,0.082707,7,156,6,13,6,26
7,C016,Male,39,208,517.807503,13,195,46.610894,30.500671,68,...,21,21,6,0.062500,7,106,10,9,9,28
8,C017,Male,36,170,369.351203,11,159,35.590809,20.441936,37,...,15,5,1,0.064706,9,48,2,59,6,24
9,C020,Female,30,222,565.967667,7,215,34.357832,23.506672,33,...,15,8,3,0.031532,11,52,78,19,8,28
10,C021,Female,29,191,433.172928,14,177,53.824557,17.917995,8,...,17,6,7,0.073298,61,20,26,3,14,28
11,C024,Female,42,194,288.786743,18,176,28.894366,29.007836,71,...,9,12,1,0.092784,5,102,7,8,16,24
12,C025,Female,24,159,359.124353,17,142,33.020450,16.108157,31,...,16,6,2,0.106918,5,39,41,3,2,25
13,C028,Male,50,204,858.494425,18,186,90.978381,35.432651,91,...,14,6,1,0.088235,13,120,2,5,2,23
14,C029,Male,34,142,348.855143,6,136,42.245812,19.796235,31,...,6,0,3,0.042254,30,59,6,0,0,25
15,C032,Female,63,305,556.955603,20,285,29.614194,23.652023,36,...,35,22,31,0.065574,13,72,66,21,6,18

In [15]:
df_complexpie['Age'] = pd.to_numeric(df_complexpie['Age'], errors='coerce')
age_summary_cp=df_complexpie['Age'].describe()
age_summary_cp

count    16.000000
mean     25.375000
std       3.630886
min      18.000000
25%      24.000000
50%      25.000000
75%      26.500000
max      35.000000
Name: Age, dtype: float64

In [16]:
gender_counts=df_complexpie['Gender'].value_counts()
gender_counts

Gender
Female    11
Male       5
Name: count, dtype: int64

#### Demographic Info - Simple Pie

In [17]:
demo_simplepie=pd.read_csv('Features_SimplePie_Action.csv')

In [18]:
demo_simplepie

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Apple Interactions - Add Apples,...,Put pie in oven,Add butter,Add crust top,Add water,Error to Actions Ratio,Object Count - Add sugar,Object Count - Add apples,Object Count - Add cinnamon,Object Count - Stir bowl,Object Count - Add bottom crust
0,C002,Female,28,231,441.284316,30,201,50.340261,24.617067,42,...,12,8,23,22,0.129870,55,68,4,6,6
1,C004,Male,30,106,267.087071,10,96,29.587162,11.430422,28,...,7,9,5,2,0.094340,21,36,2,6,3
2,C005,Female,46,224,420.203874,24,200,42.595820,26.613052,52,...,33,7,3,3,0.107143,16,79,48,4,2
3,C010,Female,54,189,391.381875,29,160,32.157613,22.471396,66,...,15,2,22,8,0.153439,6,79,5,3,2
4,C014,Female,32,252,373.759417,12,240,31.466625,37.179173,70,...,10,16,4,8,0.047619,6,126,6,3,13
5,C015,Female,33,148,179.116540,7,141,16.728146,25.625626,65,...,7,7,4,6,0.047297,5,90,2,13,2
6,C018,Male,50,225,460.775250,37,188,62.982422,28.409025,70,...,7,7,6,9,0.164444,31,94,2,7,20
7,C019,Female,40,149,251.291784,14,135,23.819270,14.073831,39,...,7,10,21,1,0.093960,7,48,24,5,5
8,C023,Female,52,179,332.910903,17,162,30.494925,20.847498,58,...,25,8,4,4,0.094972,13,75,5,12,5
9,C026,Female,33,269,615.561959,18,251,61.220314,28.549479,39,...,13,12,6,2,0.066914,81,57,44,16,7
10,C027,Female,41,194,329.012081,17,177,31.455011,33.374459,81,...,7,10,3,4,0.087629,13,113,4,13,4
11,C030,Female,39,159,321.537060,33,126,37.353355,23.183458,42,...,9,14,5,2,0.207547,9,75,2,4,3
12,C031,Male,61,149,241.995862,28,121,17.418283,20.353691,62,...,11,8,8,2,0.187919,5,70,4,3,3

In [19]:
df_simplepie = pd.merge( demo_simplepie, df , on='Participant', how='inner')
df_simplepie

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Apple Interactions - Add Apples,...,Add butter,Add crust top,Add water,Error to Actions Ratio,Object Count - Add sugar,Object Count - Add apples,Object Count - Add cinnamon,Object Count - Stir bowl,Object Count - Add bottom crust,Age
0,C002,Female,28,231,441.284316,30,201,50.340261,24.617067,42,...,8,23,22,0.129870,55,68,4,6,6,26
1,C004,Male,30,106,267.087071,10,96,29.587162,11.430422,28,...,9,5,2,0.094340,21,36,2,6,3,26
2,C005,Female,46,224,420.203874,24,200,42.595820,26.613052,52,...,7,3,3,0.107143,16,79,48,4,2,24
3,C010,Female,54,189,391.381875,29,160,32.157613,22.471396,66,...,2,22,8,0.153439,6,79,5,3,2,26
4,C014,Female,32,252,373.759417,12,240,31.466625,37.179173,70,...,16,4,8,0.047619,6,126,6,3,13,25
5,C015,Female,33,148,179.116540,7,141,16.728146,25.625626,65,...,7,4,6,0.047297,5,90,2,13,2,25
6,C018,Male,50,225,460.775250,37,188,62.982422,28.409025,70,...,7,6,9,0.164444,31,94,2,7,20,26
7,C019,Female,40,149,251.291784,14,135,23.819270,14.073831,39,...,10,21,1,0.093960,7,48,24,5,5,22
8,C023,Female,52,179,332.910903,17,162,30.494925,20.847498,58,...,8,4,4,0.094972,13,75,5,12,5,23
9,C026,Female,33,269,615.561959,18,251,61.220314,28.549479,39,...,12,6,2,0.066914,81,57,44,16,7,24
10,C027,Female,41,194,329.012081,17,177,31.455011,33.374459,81,...,10,3,4,0.087629,13,113,4,13,4,26
11,C030,Female,39,159,321.537060,33,126,37.353355,23.183458,42,...,14,5,2,0.207547,9,75,2,4,3,25
12,C031,Male,61,149,241.995862,28,121,17.418283,20.353691,62,...,8,8,2,0.187919,5,70,4,3,3,25

In [20]:
df_simplepie['Age'] = pd.to_numeric(df_simplepie['Age'], errors='coerce')
age_summary_sp=df_simplepie['Age'].describe()
age_summary_sp

count    13.000000
mean     24.846154
std       1.281025
min      22.000000
25%      24.000000
50%      25.000000
75%      26.000000
max      26.000000
Name: Age, dtype: float64

In [21]:
gender_counts=df_simplepie['Gender'].value_counts()
gender_counts

Gender
Female    10
Male       3
Name: count, dtype: int64

#### Demographic Info - Complex Stew

In [22]:
demo_complexstew=pd.read_csv('Features_ComplexStew_Action.csv')

In [23]:
demo_complexstew

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Add Onion,Add Tomtato,Add Beef,Add Carrot,Add Potato,Error to Actions Ratio,Object Count - Add Tomtato,Object Count - Add Potato,Object Count - Add Carrot,Object Count - Add Onion
0,C002,Female,28,236,379.717201,7,229,27.092263,19.574360,31,20,57,49,39,0.029661,20,39,47,30
1,C004,Male,30,230,448.278247,11,219,33.319354,20.709633,63,22,34,46,30,0.047826,20,30,40,61
2,C005,Female,46,244,630.314119,26,218,46.989878,25.988031,27,27,36,31,0,0.106557,24,0,31,27
3,C011,Female,34,317,441.342282,68,249,40.778881,34.486874,57,26,98,0,68,0.214511,25,48,0,50
4,C014,Female,32,149,301.389534,13,136,14.376381,13.527339,20,26,0,44,18,0.087248,26,18,43,20
5,C015,Female,33,328,477.137853,18,310,34.377668,30.626060,34,35,89,72,56,0.054878,35,52,67,33
6,C018,Male,50,175,311.229064,6,169,17.584074,15.629388,24,25,46,35,23,0.034286,24,23,34,22
7,C019,Female,40,222,392.315865,3,219,29.693535,24.380320,81,19,29,41,26,0.013514,19,26,41,81
8,C023,Female,52,296,512.460218,7,289,52.261754,36.080774,38,26,105,80,29,0.023649,26,29,79,37
9,C026,Female,33,202,392.338178,1,201,20.106392,15.597721,47,22,36,34,29,0.004950,21,29,34,47
10,C027,Female,41,167,288.690354,4,163,16.154880,15.874858,22,18,43,44,18,0.023952,18,18,44,22
11,C031,Male,61,303,631.112215,46,257,59.936255,31.941092,52,20,108,41,33,0.151815,19,32,37,42

In [24]:
df_complexstew = pd.merge( demo_complexstew, df , on='Participant', how='inner')
df_complexstew

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Add Onion,Add Tomtato,Add Beef,Add Carrot,Add Potato,Error to Actions Ratio,Object Count - Add Tomtato,Object Count - Add Potato,Object Count - Add Carrot,Object Count - Add Onion,Age
0,C002,Female,28,236,379.717201,7,229,27.092263,19.574360,31,20,57,49,39,0.029661,20,39,47,30,26
1,C004,Male,30,230,448.278247,11,219,33.319354,20.709633,63,22,34,46,30,0.047826,20,30,40,61,26
2,C005,Female,46,244,630.314119,26,218,46.989878,25.988031,27,27,36,31,0,0.106557,24,0,31,27,24
3,C011,Female,34,317,441.342282,68,249,40.778881,34.486874,57,26,98,0,68,0.214511,25,48,0,50,25
4,C014,Female,32,149,301.389534,13,136,14.376381,13.527339,20,26,0,44,18,0.087248,26,18,43,20,25
5,C015,Female,33,328,477.137853,18,310,34.377668,30.626060,34,35,89,72,56,0.054878,35,52,67,33,25
6,C018,Male,50,175,311.229064,6,169,17.584074,15.629388,24,25,46,35,23,0.034286,24,23,34,22,26
7,C019,Female,40,222,392.315865,3,219,29.693535,24.380320,81,19,29,41,26,0.013514,19,26,41,81,22
8,C023,Female,52,296,512.460218,7,289,52.261754,36.080774,38,26,105,80,29,0.023649,26,29,79,37,23
9,C026,Female,33,202,392.338178,1,201,20.106392,15.597721,47,22,36,34,29,0.004950,21,29,34,47,24
10,C027,Female,41,167,288.690354,4,163,16.154880,15.874858,22,18,43,44,18,0.023952,18,18,44,22,26
11,C031,Male,61,303,631.112215,46,257,59.936255,31.941092,52,20,108,41,33,0.151815,19,32,37,42,25

In [25]:
df_complexstew['Age'] = pd.to_numeric(df_complexstew['Age'], errors='coerce')
age_summary_cs=df_complexstew['Age'].describe()
age_summary_cs

count    12.000000
mean     24.750000
std       1.288057
min      22.000000
25%      24.000000
50%      25.000000
75%      26.000000
max      26.000000
Name: Age, dtype: float64

In [26]:
gender_counts=df_complexstew['Gender'].value_counts()
gender_counts

Gender
Female    9
Male      3
Name: count, dtype: int64

#### Demographic Info - Simple Stew

In [27]:
demo_simplestew=pd.read_csv('Features_SimpleStew_Action.csv')

In [28]:
demo_simplestew

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Add Onion,Add Tomtato,Add Beef,Add Carrot,Add Potato,Error to Actions Ratio,Object Count - Add Tomtato,Object Count - Add Potato,Object Count - Add Carrot,Object Count - Add Onion
0,C001,Female,36,180,241.813972,3,177,19.373010,15.033296,33,25,35,40,23,0.016667,25,23,39,33
1,C003,Female,58,212,368.939742,13,199,35.630609,18.443909,35,18,59,35,19,0.061321,17,17,34,35
2,C006,Male,42,216,258.609221,45,171,19.902276,24.180800,26,24,33,83,23,0.208333,22,21,53,25
3,C008,Female,34,290,316.882270,9,281,20.357014,27.190685,55,34,72,70,17,0.031034,34,16,69,53
4,C009,Female,24,344,450.877417,16,328,47.383847,46.421259,0,32,153,63,27,0.046512,32,27,63,0
5,C012,Female,54,163,240.627667,1,162,14.958293,15.122096,28,20,42,35,22,0.006135,20,22,35,28
6,C013,Female,48,314,530.895012,35,279,35.520103,25.382409,48,29,74,64,22,0.111465,25,21,62,45
7,C016,Male,39,183,185.527859,16,167,11.689684,18.523559,24,21,60,35,21,0.087432,21,20,33,21
8,C017,Male,36,218,335.729737,12,206,25.446555,20.384090,57,26,49,40,20,0.055046,24,19,38,55
9,C020,Female,30,212,320.340694,1,211,17.424497,18.023442,54,23,30,40,33,0.004717,23,33,40,54
10,C021,Female,29,310,481.343316,14,296,35.932085,26.072548,49,29,83,62,30,0.045161,28,30,57,49
11,C024,Female,42,156,188.807745,4,152,10.711102,14.017449,19,17,43,33,22,0.025641,17,22,32,19
12,C025,Female,24,160,317.064713,12,148,21.660530,15.033296,42,18,28,35,20,0.075000,17,19,35,36
13,C028,Male,50,180,283.077166,3,177,19.425701,17.441967,34,22,45,43,20,0.016667,21,19,43,34
14,C032,Female,63,181,214.467324,5,176,16.958552,19.996944,34,17,64,31,17,0.027624,17,17,31,34

In [29]:
df_simplestew = pd.merge( demo_simplestew, df , on='Participant', how='inner')
df_simplestew

,Participant,Gender,Block Design Raw Score,Total Actions,Total Time Spent,Total Missed Interactions,Total Object Interactions,Time Spent S.D,Action Count S.D,Add Onion,Add Tomtato,Add Beef,Add Carrot,Add Potato,Error to Actions Ratio,Object Count - Add Tomtato,Object Count - Add Potato,Object Count - Add Carrot,Object Count - Add Onion,Age
0,C001,Female,36,180,241.813972,3,177,19.373010,15.033296,33,25,35,40,23,0.016667,25,23,39,33,21
1,C003,Female,58,212,368.939742,13,199,35.630609,18.443909,35,18,59,35,19,0.061321,17,17,34,35,25
2,C006,Male,42,216,258.609221,45,171,19.902276,24.180800,26,24,33,83,23,0.208333,22,21,53,25,35
3,C008,Female,34,290,316.882270,9,281,20.357014,27.190685,55,34,72,70,17,0.031034,34,16,69,53,25
4,C009,Female,24,344,450.877417,16,328,47.383847,46.421259,0,32,153,63,27,0.046512,32,27,63,0,26
5,C012,Female,54,163,240.627667,1,162,14.958293,15.122096,28,20,42,35,22,0.006135,20,22,35,28,25
6,C013,Female,48,314,530.895012,35,279,35.520103,25.382409,48,29,74,64,22,0.111465,25,21,62,45,26
7,C016,Male,39,183,185.527859,16,167,11.689684,18.523559,24,21,60,35,21,0.087432,21,20,33,21,28
8,C017,Male,36,218,335.729737,12,206,25.446555,20.384090,57,26,49,40,20,0.055046,24,19,38,55,24
9,C020,Female,30,212,320.340694,1,211,17.424497,18.023442,54,23,30,40,33,0.004717,23,33,40,54,28
10,C021,Female,29,310,481.343316,14,296,35.932085,26.072548,49,29,83,62,30,0.045161,28,30,57,49,28
11,C024,Female,42,156,188.807745,4,152,10.711102,14.017449,19,17,43,33,22,0.025641,17,22,32,19,24
12,C025,Female,24,160,317.064713,12,148,21.660530,15.033296,42,18,28,35,20,0.075000,17,19,35,36,25
13,C028,Male,50,180,283.077166,3,177,19.425701,17.441967,34,22,45,43,20,0.016667,21,19,43,34,23
14,C032,Female,63,181,214.467324,5,176,16.958552,19.996944,34,17,64,31,17,0.027624,17,17,31,34,18

In [30]:
df_simplestew['Age'] = pd.to_numeric(df_simplestew['Age'], errors='coerce')
age_summary_ss=df_simplestew['Age'].describe()
age_summary_ss

count    15.000000
mean     25.400000
std       3.756898
min      18.000000
25%      24.000000
50%      25.000000
75%      27.000000
max      35.000000
Name: Age, dtype: float64

In [31]:
gender_counts=df_simplestew['Gender'].value_counts()
gender_counts

Gender
Female    11
Male       4
Name: count, dtype: int64

#### T-test between Simple Pie and Complex Pie

In [32]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(df_simplepie['Age'], df_complexpie['Age'], nan_policy='omit')
t_stat, p_value

(-0.49908196523771886, 0.6217638963001795)

#### T-test between Simple Stew and Complex Stew

In [33]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(df_simplestew['Age'], df_complexstew['Age'], nan_policy='omit')
t_stat, p_value

(0.5711651554298773, 0.5729870207735634)